language: php

php:
  - 8.0
  - 8.1

before_script:
  - 'composer update --prefer-source'

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq postfix
  - smtp-sink -d "%d.%H.%M.%S" localhost:2500 1000 &

script: vendor/bin/codecept run
